In [28]:
import numpy as np

import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly() 

True

#### Only variable and constants are compatible with eager execution 

In [18]:
W = tf.Variable(6, name = 'var_W')

x = tf.constant([10, 10], name = 'x')

b = tf.Variable(3, name = 'constant_b')

In [19]:
W

<tf.Variable 'var_W:0' shape=() dtype=int32, numpy=6>

In [20]:
x

<tf.Tensor: id=64, shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [21]:
b

<tf.Variable 'constant_b:0' shape=() dtype=int32, numpy=3>

In [22]:
y = W * x + b

In [23]:
y

<tf.Tensor: id=80, shape=(2,), dtype=int32, numpy=array([63, 63], dtype=int32)>

In [24]:
print(y)

tf.Tensor([63 63], shape=(2,), dtype=int32)


In [31]:
print(W*x)

tf.Tensor([60 60], shape=(2,), dtype=int32)


https://www.tensorflow.org/guide/eager#work_with_graphs

In [32]:
np_result = np.multiply(W, x)

np_result

array([<tf.Tensor: id=108, shape=(), dtype=int32, numpy=60>,
       <tf.Tensor: id=111, shape=(), dtype=int32, numpy=60>], dtype=object)

In [33]:
W.numpy()

6

In [34]:
y.numpy()

array([63, 63], dtype=int32)