## Interoperablity between Numpy arrays and Pytorch Tensors

In [29]:
import numpy as np
import torch

#### Converting tensor to numpy arrays

In [30]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.1199, 0.5962, 0.1121],
        [0.9186, 0.0819, 0.8811],
        [0.3523, 0.6303, 0.2187],
        [0.3913, 0.3043, 0.2952]])

In [31]:
type(tensor)

torch.Tensor

### The numpy arrays use the same memory as the PyTorch tensor

In [32]:
numpy_from_tensor = tensor.numpy()                   
numpy_from_tensor

array([[0.11985421, 0.5962059 , 0.11210066],
       [0.91856444, 0.08194387, 0.88110924],
       [0.35226905, 0.6303377 , 0.21870357],
       [0.3913232 , 0.30429846, 0.29519582]], dtype=float32)

In [33]:
type(numpy_from_tensor)

numpy.ndarray

In [34]:
torch.is_tensor(tensor)

True

In [35]:
torch.is_tensor(numpy_from_tensor)

False

#### The NumPy array and the Torch tensor share memory

In [58]:
numpy_from_tensor[0, 0] = 100.0

numpy_from_tensor

array([[1.0000000e+02, 5.9620589e-01, 1.1210066e-01],
       [9.1856444e-01, 8.1943870e-02, 8.8110924e-01],
       [3.5226905e-01, 6.3033772e-01, 2.1870357e-01],
       [3.9132321e-01, 3.0429846e-01, 2.9519582e-01]], dtype=float32)

In [59]:
tensor

tensor([[1.0000e+02, 5.9621e-01, 1.1210e-01],
        [9.1856e-01, 8.1944e-02, 8.8111e-01],
        [3.5227e-01, 6.3034e-01, 2.1870e-01],
        [3.9132e-01, 3.0430e-01, 2.9520e-01]])

#### Converting a numpy array to a Tensor

In [60]:
numpy_arr = np.array([[1.0, 2.0, 3.0], 
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])

numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [61]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [62]:
type(tensor_from_numpy)

torch.Tensor

In [63]:
torch.is_tensor(tensor_from_numpy)

True

#### The Numpy arrays and Tensor share the same memory
The tensor and numpy_from_tensor are shallow copies and share the same memory as the original numpy array. Modifying the original array affects the values of both tensor and numpy_from_tensor

In [64]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [65]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

#### Convert the data into a torch.Tensor. 

If the data is already a Tensor with the same dtype and device, no copy will be performed, otherwise a new Tensor will be returned

In [66]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [67]:
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8])

In [68]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [69]:
tensor_from_array_one

tensor([4, 5])

#### torch.tensor() reads out the data from whatever it is passed, and constructs a leaf variable

In [72]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [73]:
tensor_from_array_two = torch.tensor(np_array_two)

tensor_from_array_two

tensor([2, 2])

#### in this method the tensor and array do not share memory

In [74]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [75]:
tensor_from_array_two

tensor([2, 2])