In [38]:
import torch 

from torch.autograd import Variable

#### We create a Variable with Float tensor

The return value is not a variable instead it is a tensor

In [39]:
var = Variable(torch.FloatTensor([9]))
var

tensor([9.])

In [40]:
var.requires_grad

False

In [41]:
var.requires_grad_()

tensor([9.], requires_grad=True)

#### We create two weight variables with gradients enabled

In [42]:
w1 = Variable(torch.FloatTensor([3]), requires_grad = True)
w2 = Variable(torch.FloatTensor([7]), requires_grad = True)

In [43]:
w1

tensor([3.], requires_grad=True)

In [44]:
w2

tensor([7.], requires_grad=True)

#### We create two more variables using the weights

In [50]:
result_var = var * w1

result_var 

tensor([27.], grad_fn=<MulBackward0>)

#### New variables derive enabled gradients from weights

In [51]:
result_var.requires_grad

True

In [52]:
result_var.backward()

In [53]:
w1.grad

tensor([18.])

In [56]:
w2.grad

In [57]:
var.grad

tensor([6.])